// Copyright (c) 2026 CS-Fusion. All Rights Reserved.
//
// Project GameInstance.
//
// Under Fusion the UGameInstance is itself networked and survives ChangeWorld
// for as long as the UFusionClient lives, which makes it the only RPC target
// guaranteed to resolve on every connected peer regardless of which map they
// are on. Global, non-actor traffic (announcements, kill feed, match events)
// therefore lives here rather than on the GameState.
//
// Note: built-in Server/Client/NetMulticast markup does NOT route on a
// UGameInstance because it is not an actor. Global RPCs must use
// SEND_FUSIONRPC.

#pragma once

#include "CoreMinimal.h"
#include "Core/CSFusionCompat.h"
#include "Engine/GameInstance.h"

#if CS_WITH_FUSION
#include "CSGameInstance.fusion.h"
#endif

#include "CSGameInstance.generated.h"

class UCSSessionSubsystem;

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FCSAnnouncement, const FString&, Message);

UCLASS(Config = Game)
class CSFUSION_API UCSGameInstance : public UGameInstance
{
	GENERATED_BODY()
	FUSION_BODY();

public:
	virtual void Init() override;
	virtual void Shutdown() override;

	/**
	 * Broadcast a short room-wide message to every connected peer.
	 *
	 * Authority-gated: only the Master Client may announce, so a modified
	 * client cannot spam the room. Call BroadcastAnnouncement(); the transport
	 * split is handled for you.
	 */
	UFUNCTION(BlueprintCallable, Category = "CS|Net")
	void BroadcastAnnouncement(const FString& Message);

	UPROPERTY(BlueprintAssignable, Category = "CS|Net")
	FCSAnnouncement OnAnnouncement;

	UFUNCTION(BlueprintPure, Category = "CS|Net")
	UCSSessionSubsystem* GetSessionSubsystem() const;

#if CS_WITH_FUSION
	/**
	 * Wire RPC. The body is generated by the Fusion UBT plugin; never define
	 * it. Do not call directly - go through BroadcastAnnouncement().
	 */
	SEND_FUSIONRPC(TargetAllClients)
	void RpcAnnouncement(const FString& Message);
#endif

	/** Receive side. Runs on every peer (including the sender). */
	void RpcAnnouncement_Receive(const FString& Message);
};
