// Copyright (c) 2026 CS-Fusion. All Rights Reserved.
//
// Project GameInstance.
//
// Under Fusion the UGameInstance is itself networked and survives ChangeWorld
// for as long as the UFusionClient lives, which makes it the only RPC target
// guaranteed to resolve on every connected peer regardless of which map they
// are on. Global, non-actor traffic (announcements, kill feed, match events)
// therefore lives here rather than on the GameState.
//
// Note: built-in Server/Client/NetMulticast markup does NOT route on a
// UGameInstance because it is not an actor. Global RPCs must use
// SEND_FUSIONRPC.

#pragma once

#include "CoreMinimal.h"
#include "Core/CSFusionCompat.h"
#include "Engine/GameInstance.h"

// Must precede the .generated.h include. FUSION_BODY() expands into this.
#include "CSGameInstance.fusion.h"
#include "CSGameInstance.generated.h"

class UCSSessionSubsystem;

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FCSAnnouncement, const FString&, Message);

UCLASS(Config = Game)
class CSFUSION_API UCSGameInstance : public UGameInstance
{
	GENERATED_BODY()
	FUSION_BODY();

public:
	virtual void Init() override;
	virtual void OnStart() override;
	virtual void Shutdown() override;

	/**
	 * Broadcast a short room-wide message to every connected peer.
	 *
	 * Authority-gated: only the Master Client may announce, so a modified
	 * client cannot spam the room. Call BroadcastAnnouncement(); the transport
	 * split is handled for you.
	 */
	UFUNCTION(BlueprintCallable, Category = "CS|Net")
	void BroadcastAnnouncement(const FString& Message);

	UPROPERTY(BlueprintAssignable, Category = "CS|Net")
	FCSAnnouncement OnAnnouncement;

	UFUNCTION(BlueprintPure, Category = "CS|Net")
	UCSSessionSubsystem* GetSessionSubsystem() const;

	/**
	 * ALPHA ONLY - stand-in for the main menu (Stage 5).
	 *
	 * With no UI, nothing would ever call HostOrJoin and the packaged build
	 * would never reach Photon. So the build auto-joins a room shortly after
	 * start. Two launched clients with the same room name meet each other.
	 *
	 * Command line overrides:
	 *   -room=NAME        room to join or create   (default: cs-alpha)
	 *   -region=CODE      force a Photon region, e.g. eu / us
	 *   -maxplayers=N     room capacity            (default: 8)
	 *   -noautoconnect    stay offline
	 *
	 * Delete this once the menu exists.
	 */
	UFUNCTION(BlueprintCallable, Category = "CS|Net")
	void AutoConnectFromCommandLine();

	/**
	 * Wire RPC. The body is generated by the Fusion UBT plugin; never define
	 * it. Do not call directly - go through BroadcastAnnouncement().
	 *
	 * Not wrapped in any #if: UHT would skip an unrecognised directive and the
	 * generated body would never appear. See Core/CSFusionCompat.h.
	 *
	 * FString MUST be a plain non-const reference here. FusionPropertyParser
	 * rejects both `const FString&` ("expects FString to not have const") and
	 * by-value FString ("expects FString to be a &"). That is why the public
	 * BroadcastAnnouncement() takes const& and copies into a local.
	 */
	SEND_FUSIONRPC(TargetAllClients)
	void RpcAnnouncement(FString& Message);

	/** Receive side. Runs on every peer (including the sender). */
	void RpcAnnouncement_Receive(FString& Message);
};
