// Copyright (c) 2026 CS-Fusion. All Rights Reserved.
//
// Character animation written entirely in C++ - no Animation Blueprint.
//
// An Animation Blueprint is a binary graph asset: it cannot be generated by
// the bootstrap script, reviewed in a diff or merged. Instead this instance
// supplies its own FAnimInstanceProxy whose Evaluate() builds the pose by
// sampling sequences and blending them with FAnimationRuntime - the same
// primitives the graph nodes use.
//
// Layers, bottom to top:
//   1. Locomotion: idle / walk / jog, 8 directions, phase-synced, speed-scaled
//   2. Falling loop, blended in while airborne
//   3. Death clip, replacing everything (held on the last frame)
//   4. Upper-body actions: reload, equip, dry fire (per-bone from spine_01)
//   5. Additive aim up/down (third person only; in first person the camera
//      pitch already rotates the arms)
//   6. Additive recoil and hit reaction
//
// All timing is advanced on the game thread in PreUpdateAnimation and handed
// to the proxy as a snapshot, so the worker-thread Evaluate only reads.
//
// The instance is driven by ACSCharacter: it reads movement from the owning
// pawn and receives one-shot triggers (PlayFire, PlayReload, ...) from the
// character, which in turn gets them from replicated state - so every peer
// animates every player the same way.

#pragma once

#include "CoreMinimal.h"
#include "Animation/AnimInstance.h"
#include "Animation/AnimInstanceProxy.h"
#include "Weapons/CSWeaponDefinition.h"
#include "CSAnimInstance.generated.h"

class UAnimSequence;

/** Everything Evaluate needs, copied from the game thread each frame. */
struct FCSAnimSnapshot
{
	const UAnimSequence* Idle = nullptr;
	const UAnimSequence* Walk[8] = {};
	const UAnimSequence* Jog[8] = {};
	const UAnimSequence* Fall = nullptr;
	const UAnimSequence* AimUp = nullptr;
	const UAnimSequence* AimDown = nullptr;
	const UAnimSequence* Fire = nullptr;
	const UAnimSequence* Upper = nullptr;		// reload / equip / dry fire, whichever is active
	const UAnimSequence* HitReact = nullptr;
	const UAnimSequence* Death = nullptr;

	float IdleTime = 0.f;
	float LocoPhase = 0.f;			// 0..1, shared by every walk/jog clip
	float DirectionDeg = 0.f;		// 0 = forward, clockwise
	float WalkAlpha = 0.f;			// idle -> walk
	float JogAlpha = 0.f;			// walk -> jog
	float FallAlpha = 0.f;
	float FallTime = 0.f;
	float AimPitch = 0.f;			// degrees, + = up
	bool bApplyAim = true;
	/** First person scales upper-body actions down so the gun stays in view. */
	float UpperWeightScale = 1.f;

	float FireTime = -1.f;			// < 0 = inactive
	float UpperTime = -1.f;
	float UpperAlpha = 0.f;
	float HitTime = -1.f;
	float DeathTime = -1.f;
	float DeathAlpha = 0.f;
};

struct FCSAnimInstanceProxy : public FAnimInstanceProxy
{
	FCSAnimInstanceProxy() = default;
	explicit FCSAnimInstanceProxy(UAnimInstance* InInstance) : FAnimInstanceProxy(InInstance) {}

	virtual void PreUpdate(UAnimInstance* InAnimInstance, float DeltaSeconds) override;
	virtual bool Evaluate(FPoseContext& Output) override;

private:
	void SampleDirectional(const UAnimSequence* const Clips[8], FPoseContext& Out) const;

	FCSAnimSnapshot Snapshot;
};

UCLASS(Transient, NotBlueprintable)
class CSFUSION_API UCSAnimInstance : public UAnimInstance
{
	GENERATED_BODY()

public:
	/** First person: no aim offset (the camera pitches the whole mesh). */
	void SetFirstPerson(bool bInFirstPerson) { bFirstPerson = bInFirstPerson; }

	/** Swaps the whole animation set; plays the equip clip unless bInstant. */
	void SetStance(ECSWeaponStance NewStance, bool bInstant = false);

	void PlayFire();
	void PlayReload(float DurationSeconds);
	void PlayEquip();
	void PlayDryFire();
	void CancelUpperBody();
	void PlayHitReact(bool bFromFront);

	/** Direction: 0 front, 1 back, 2 left, 3 right. */
	void PlayDeath(int32 Direction);
	void ResetAlive();

	bool IsPlayingUpperBody() const { return UpperTime >= 0.f; }
	bool IsDead() const { return DeathTime >= 0.f; }
	float GetGroundSpeed() const { return GroundSpeed; }
	ECSWeaponStance GetStance() const { return Stance; }

protected:
	virtual void NativeInitializeAnimation() override;
	virtual void PreUpdateAnimation(float DeltaSeconds) override;
	virtual FAnimInstanceProxy* CreateAnimInstanceProxy() override;
	virtual void DestroyAnimInstanceProxy(FAnimInstanceProxy* InProxy) override;

private:
	friend struct FCSAnimInstanceProxy;

	void ResolveClips();
	void AdvanceGameThread(float DeltaSeconds);

	/** Resolved sequences; UPROPERTY keeps them loaded. */
	UPROPERTY(Transient) TObjectPtr<UAnimSequence> IdleClip;
	UPROPERTY(Transient) TArray<TObjectPtr<UAnimSequence>> WalkClips;
	UPROPERTY(Transient) TArray<TObjectPtr<UAnimSequence>> JogClips;
	UPROPERTY(Transient) TObjectPtr<UAnimSequence> FallClip;
	UPROPERTY(Transient) TObjectPtr<UAnimSequence> AimUpClip;
	UPROPERTY(Transient) TObjectPtr<UAnimSequence> AimDownClip;
	UPROPERTY(Transient) TObjectPtr<UAnimSequence> FireClip;
	UPROPERTY(Transient) TObjectPtr<UAnimSequence> ReloadClip;
	UPROPERTY(Transient) TObjectPtr<UAnimSequence> EquipClip;
	UPROPERTY(Transient) TObjectPtr<UAnimSequence> DryFireClip;
	UPROPERTY(Transient) TObjectPtr<UAnimSequence> HitFrontClip;
	UPROPERTY(Transient) TObjectPtr<UAnimSequence> HitBackClip;
	UPROPERTY(Transient) TArray<TObjectPtr<UAnimSequence>> DeathClips;
	UPROPERTY(Transient) TObjectPtr<UAnimSequence> ActiveUpperClip;
	UPROPERTY(Transient) TObjectPtr<UAnimSequence> ActiveHitClip;
	UPROPERTY(Transient) TObjectPtr<UAnimSequence> ActiveDeathClip;

	ECSWeaponStance Stance = ECSWeaponStance::Pistol;
	bool bClipsResolved = false;
	bool bFirstPerson = false;

	float WalkClipSpeed = 180.f;
	float JogClipSpeed = 420.f;

	// Game-thread state
	float GroundSpeed = 0.f;
	float DirectionDeg = 0.f;
	float AimPitch = 0.f;
	float IdleTime = 0.f;
	float LocoPhase = 0.f;
	float FallAlpha = 0.f;
	float FallTime = 0.f;
	float FireTime = -1.f;
	float UpperTime = -1.f;
	float UpperRate = 1.f;
	float HitTime = -1.f;
	float DeathTime = -1.f;
	float DeathAlpha = 0.f;
};
