// Copyright (c) 2026 CS-Fusion. All Rights Reserved.
//
// The bot Behavior Tree and its Blackboard, built in C++.
//
// A Behavior Tree asset is a binary graph that cannot be generated by the
// bootstrap script or reviewed in a diff, so the tree is assembled from the
// same runtime node classes the editor would produce (UBTComposite_Selector,
// UBTComposite_Sequence, decorators, tasks, a service) and handed to
// RunBehaviorTree. The engine's UBehaviorTreeManager initialises it exactly
// like a loaded asset.
//
//   Selector  [service: Bot brain]
//   |- Sequence "Fight"        [TargetActor is set, aborts both]
//   |    '- Engage target
//   |- Sequence "Investigate"  [LastKnownLocation is set, aborts both]
//   |    '- Move to LastKnownLocation (clears it on arrival)
//   |- Sequence "Loot"         [LootTarget is set, aborts both]
//   |    |- Move to LootTarget
//   |    '- Pick up loot
//   '- Sequence "Patrol"
//        |- Find patrol point
//        |- Move to PatrolLocation
//        '- Pause 0.5-1.5 s

#pragma once

#include "CoreMinimal.h"

class UBehaviorTree;
class UBlackboardData;

namespace CSBotBehavior
{
	extern const FName KeyTarget;
	extern const FName KeyLastKnownLocation;
	extern const FName KeyLootTarget;
	extern const FName KeyPatrolLocation;

	/** Builds a fresh tree (and its blackboard) owned by Outer. */
	UBehaviorTree* BuildTree(UObject* Outer, UBlackboardData*& OutBlackboard);
}
