[/Script/Engine.InputSettings]
bAltEnterTogglesFullscreen=True
bCaptureMouseOnLaunch=True
DefaultViewportMouseCaptureMode=CapturePermanently_IncludingInitialMouseDown
DefaultViewportMouseLockMode=LockOnCapture
bEnableMouseSmoothing=False
bViewAccelerationEnabled=False
bDefaultViewportMouseLock=True

; Enhanced Input is required by ACSCharacter.
DefaultPlayerInputClass=/Script/EnhancedInput.EnhancedPlayerInput
DefaultInputComponentClass=/Script/EnhancedInput.EnhancedInputComponent

[/Script/EnhancedInput.EnhancedInputDeveloperSettings]
bEnableUserSettings=True
bSendTriggeredEventsWhenInputIsFlushed=False
