// Copyright (c) 2026 CS-Fusion. All Rights Reserved.
//
// Game-wide sounds and the sound classes the settings screen controls.
// Project Settings > Game > CS Audio. The default assets under /Game/Audio
// are generated by Scripts/generate_audio.py (our own synthesis, no third-
// party recordings) - see docs/ASSETS.md.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DeveloperSettings.h"
#include "CSAudioSettings.generated.h"

class USoundBase;
class USoundClass;
class USoundMix;
class USoundAttenuation;

UCLASS(Config = Game, DefaultConfig, meta = (DisplayName = "CS Audio"))
class CSFUSION_API UCSAudioSettings : public UDeveloperSettings
{
	GENERATED_BODY()

public:
	UCSAudioSettings();

	static const UCSAudioSettings* Get() { return GetDefault<UCSAudioSettings>(); }

	// --- Mixing ---------------------------------------------------------------

	UPROPERTY(EditAnywhere, Config, Category = "Mixing")
	TSoftObjectPtr<USoundClass> MusicClass;

	UPROPERTY(EditAnywhere, Config, Category = "Mixing")
	TSoftObjectPtr<USoundClass> EffectsClass;

	/** Pushed once; its class overrides carry the music / effects volumes. */
	UPROPERTY(EditAnywhere, Config, Category = "Mixing")
	TSoftObjectPtr<USoundMix> VolumeMix;

	/** Distance falloff for every 3D gameplay sound. */
	UPROPERTY(EditAnywhere, Config, Category = "Mixing")
	TSoftObjectPtr<USoundAttenuation> WorldAttenuation;

	// --- Gameplay -------------------------------------------------------------

	/** One is picked at random per step. */
	UPROPERTY(EditAnywhere, Config, Category = "Gameplay")
	TArray<TSoftObjectPtr<USoundBase>> Footsteps;

	UPROPERTY(EditAnywhere, Config, Category = "Gameplay")
	TSoftObjectPtr<USoundBase> JumpLand;

	UPROPERTY(EditAnywhere, Config, Category = "Gameplay")
	TSoftObjectPtr<USoundBase> BulletImpact;

	UPROPERTY(EditAnywhere, Config, Category = "Gameplay")
	TSoftObjectPtr<USoundBase> BodyHit;

	UPROPERTY(EditAnywhere, Config, Category = "Gameplay")
	TSoftObjectPtr<USoundBase> Death;

	UPROPERTY(EditAnywhere, Config, Category = "Gameplay")
	TSoftObjectPtr<USoundBase> Pickup;

	UPROPERTY(EditAnywhere, Config, Category = "Gameplay")
	TSoftObjectPtr<USoundBase> Respawn;

	// --- Feedback (2D, local player only) ------------------------------------

	UPROPERTY(EditAnywhere, Config, Category = "Feedback")
	TSoftObjectPtr<USoundBase> HitMarker;

	UPROPERTY(EditAnywhere, Config, Category = "Feedback")
	TSoftObjectPtr<USoundBase> Headshot;

	UPROPERTY(EditAnywhere, Config, Category = "Feedback")
	TSoftObjectPtr<USoundBase> KillConfirm;

	UPROPERTY(EditAnywhere, Config, Category = "Feedback")
	TSoftObjectPtr<USoundBase> Hurt;

	// --- UI / music -------------------------------------------------------------

	UPROPERTY(EditAnywhere, Config, Category = "UI")
	TSoftObjectPtr<USoundBase> UIClick;

	UPROPERTY(EditAnywhere, Config, Category = "UI")
	TSoftObjectPtr<USoundBase> UIHover;

	UPROPERTY(EditAnywhere, Config, Category = "UI")
	TSoftObjectPtr<USoundBase> MenuMusic;

	/** Distance between footsteps while walking, cm. */
	UPROPERTY(EditAnywhere, Config, Category = "Gameplay", meta = (ClampMin = "50"))
	float StepDistance = 190.f;
};
