// Copyright (c) 2026 CS-Fusion. All Rights Reserved.

#include "FX/CSEffects.h"

#include "Audio/CSAudio.h"
#include "Core/CSLog.h"
#include "Audio/CSAudioSettings.h"
#include "Components/DecalComponent.h"
#include "Engine/World.h"
#include "FX/CSTransientFX.h"
#include "Kismet/GameplayStatics.h"
#include "Materials/MaterialInterface.h"

namespace CSEffects
{
	namespace
	{
		/** Generated by the bootstrap script; /Game/FX is always cooked. */
		const TSoftObjectPtr<UMaterialInterface> BulletHoleMaterial(
			FSoftObjectPath(TEXT("/Game/FX/Materials/M_CS_BulletHole.M_CS_BulletHole")));

		constexpr float GDecalLifetime = 20.f;
	}

	void MuzzleFlash(UWorld* World, const FTransform& Muzzle, float Scale, const AActor* Owner, bool bFirstPerson)
	{
		ACSTransientFX::FParams Flash;
		Flash.Shape = ECSFXShape::Star;
		Flash.Color = FLinearColor(1.f, 0.62f, 0.22f);
		Flash.Intensity = 12.f;
		Flash.Lifetime = 0.05f;
		const float Size = 0.22f * Scale * FMath::FRandRange(0.8f, 1.2f);
		Flash.StartScale = FVector(Size);
		Flash.EndScale = FVector(Size * 1.3f);
		Flash.LightIntensity = 9000.f * Scale;
		Flash.LightRadius = 350.f;
		Flash.VisibilityOwner = Owner;
		Flash.bOnlyOwnerSee = bFirstPerson;
		Flash.bOwnerNoSee = !bFirstPerson;

		// The planes are centred; push the flash out so it starts at the muzzle.
		FTransform T = Muzzle;
		T.SetScale3D(FVector::OneVector);
		T.AddToTranslation(T.GetRotation().GetForwardVector() * Size * 50.f);
		T.ConcatenateRotation(FQuat(FVector::ForwardVector, FMath::FRandRange(0.f, PI)));
		ACSTransientFX::Spawn(World, T, Flash);
	}

	void Tracer(UWorld* World, const FVector& Start, const FVector& End, const FLinearColor& Color)
	{
		const FVector Delta = End - Start;
		const float Length = Delta.Size();
		if (Length < 50.f)
		{
			return;
		}

		ACSTransientFX::FParams Streak;
		Streak.Shape = ECSFXShape::Cylinder;
		Streak.Color = Color;
		Streak.Intensity = 20.f;
		Streak.Lifetime = 0.06f;
		// X = length in 100 cm units, Y/Z = thickness.
		Streak.StartScale = FVector(Length / 100.f, 0.012f, 0.012f);
		Streak.EndScale = FVector(Length / 100.f, 0.004f, 0.004f);
		ACSTransientFX::Spawn(World, FTransform(Delta.Rotation(), Start), Streak);
	}

	void Impact(UWorld* World, const FVector& Location, const FVector& Normal, bool bHitPlayer)
	{
		if (!World)
		{
			return;
		}
		const FVector N = Normal.IsNearlyZero() ? FVector::UpVector : Normal.GetSafeNormal();
		const UCSAudioSettings* Audio = UCSAudioSettings::Get();

		if (bHitPlayer)
		{
			ACSTransientFX::FParams Blood;
			Blood.bAdditive = false;
			Blood.Color = FLinearColor(0.45f, 0.02f, 0.02f);
			Blood.Opacity = 0.9f;
			Blood.Lifetime = 0.3f;
			Blood.StartScale = FVector(0.08f);
			Blood.EndScale = FVector(0.32f);
			ACSTransientFX::Spawn(World, FTransform(Location + N * 5.f), Blood);
			CSAudio::PlayAt(World, Audio->BodyHit, Location, 0.9f, FMath::FRandRange(0.92f, 1.08f));
			return;
		}

		// Dust puff that grows and fades.
		ACSTransientFX::FParams Dust;
		Dust.bAdditive = false;
		Dust.Color = FLinearColor(0.2f, 0.19f, 0.17f);
		Dust.Opacity = 0.85f;
		Dust.Lifetime = 0.6f;
		Dust.StartScale = FVector(0.08f);
		Dust.EndScale = FVector(0.5f);
		ACSTransientFX::Spawn(World, FTransform(Location + N * 8.f), Dust);

		// Spark flash.
		ACSTransientFX::FParams Spark;
		Spark.Color = FLinearColor(1.f, 0.7f, 0.3f);
		Spark.Intensity = 15.f;
		Spark.Lifetime = 0.07f;
		Spark.StartScale = FVector(0.06f);
		Spark.EndScale = FVector(0.02f);
		Spark.LightIntensity = 1500.f;
		Spark.LightRadius = 120.f;
		ACSTransientFX::Spawn(World, FTransform(Location + N * 2.f), Spark);

		// Bullet hole, oriented into the surface.
		if (UMaterialInterface* Decal = BulletHoleMaterial.LoadSynchronous())
		{
			const float Size = FMath::FRandRange(6.f, 8.f);
			FRotator Rotation = (-N).Rotation();
			Rotation.Roll = FMath::FRandRange(-180.f, 180.f);
			if (UDecalComponent* Hole = UGameplayStatics::SpawnDecalAtLocation(World, Decal, FVector(4.f, Size, Size), Location, Rotation, GDecalLifetime))
			{
				Hole->SetFadeScreenSize(0.001f);
				Hole->SetFadeOut(GDecalLifetime - 3.f, 3.f, false);
			}
		}

		CSAudio::PlayAt(World, Audio->BulletImpact, Location, 0.7f, FMath::FRandRange(0.85f, 1.15f));
	}
}
