// Copyright (c) 2026 CS-Fusion. All Rights Reserved.

#include "FX/CSEffects.h"

#include "Audio/CSAudio.h"
#include "Core/CSLog.h"
#include "Audio/CSAudioSettings.h"
#include "Components/DecalComponent.h"
#include "Engine/World.h"
#include "FX/CSTransientFX.h"
#include "Kismet/GameplayStatics.h"
#include "Materials/MaterialInterface.h"
#include "NiagaraComponent.h"
#include "NiagaraFunctionLibrary.h"
#include "NiagaraSystem.h"
#include "PhysicalMaterials/PhysicalMaterial.h"

namespace CSEffects
{
	namespace
	{
		/** Generated by the bootstrap script; /Game/FX is always cooked. */
		const TSoftObjectPtr<UMaterialInterface> BulletHoleMaterial(
			FSoftObjectPath(TEXT("/Game/FX/Materials/M_CS_BulletHole.M_CS_BulletHole")));

		constexpr float GDecalLifetime = 20.f;

		// v2.0 phase 3 (C10): built by the CSFXBuilder commandlet.
		TSoftObjectPtr<UNiagaraSystem> NiagaraAt(const TCHAR* Name)
		{
			return TSoftObjectPtr<UNiagaraSystem>(FSoftObjectPath(FString::Printf(TEXT("/Game/FX/Niagara/%s.%s"), Name, Name)));
		}
		const TSoftObjectPtr<UNiagaraSystem> StoneImpactSystem = NiagaraAt(TEXT("NS_Impact_Stone"));
		const TSoftObjectPtr<UNiagaraSystem> MetalImpactSystem = NiagaraAt(TEXT("NS_Impact_Metal"));
		const TSoftObjectPtr<UNiagaraSystem> WoodImpactSystem = NiagaraAt(TEXT("NS_Impact_Wood"));
		const TSoftObjectPtr<UNiagaraSystem> DirtImpactSystem = NiagaraAt(TEXT("NS_Impact_Dirt"));
		const TSoftObjectPtr<UNiagaraSystem> BloodSystem = NiagaraAt(TEXT("NS_Impact_Blood"));
		const TSoftObjectPtr<UNiagaraSystem> MuzzleSmokeSystem = NiagaraAt(TEXT("NS_MuzzleSmoke"));
		const TSoftObjectPtr<UNiagaraSystem> ShellEjectSystem = NiagaraAt(TEXT("NS_ShellEject"));
		const TSoftObjectPtr<UNiagaraSystem> ExplosionSystem = NiagaraAt(TEXT("NS_Explosion"));
		const TSoftObjectPtr<UNiagaraSystem> FlashbangSystem = NiagaraAt(TEXT("NS_FlashbangBurst"));
	}

	void MuzzleFlash(UWorld* World, const FTransform& Muzzle, float Scale, const AActor* Owner, bool bFirstPerson)
	{
		ACSTransientFX::FParams Flash;
		Flash.Shape = ECSFXShape::Star;
		Flash.Color = FLinearColor(1.f, 0.62f, 0.22f);
		Flash.Intensity = 12.f;
		Flash.Lifetime = 0.05f;
		const float Size = 0.22f * Scale * FMath::FRandRange(0.8f, 1.2f);
		Flash.StartScale = FVector(Size);
		Flash.EndScale = FVector(Size * 1.3f);
		Flash.LightIntensity = 9000.f * Scale;
		Flash.LightRadius = 350.f;
		Flash.VisibilityOwner = Owner;
		Flash.bOnlyOwnerSee = bFirstPerson;
		Flash.bOwnerNoSee = !bFirstPerson;

		// The planes are centred; push the flash out so it starts at the muzzle.
		FTransform T = Muzzle;
		T.SetScale3D(FVector::OneVector);
		T.AddToTranslation(T.GetRotation().GetForwardVector() * Size * 50.f);
		T.ConcatenateRotation(FQuat(FVector::ForwardVector, FMath::FRandRange(0.f, PI)));
		ACSTransientFX::Spawn(World, T, Flash);

		// A wisp of smoke drifting out of the barrel.
		SpawnSystem(World, MuzzleSmokeSystem, Muzzle.GetLocation(), Muzzle.Rotator());
	}

	void Tracer(UWorld* World, const FVector& Start, const FVector& End, const FLinearColor& Color)
	{
		const FVector Delta = End - Start;
		const float Length = Delta.Size();
		if (Length < 50.f)
		{
			return;
		}

		ACSTransientFX::FParams Streak;
		Streak.Shape = ECSFXShape::Cylinder;
		Streak.Color = Color;
		Streak.Intensity = 20.f;
		Streak.Lifetime = 0.06f;
		// X = length in 100 cm units, Y/Z = thickness.
		Streak.StartScale = FVector(Length / 100.f, 0.012f, 0.012f);
		Streak.EndScale = FVector(Length / 100.f, 0.004f, 0.004f);
		ACSTransientFX::Spawn(World, FTransform(Delta.Rotation(), Start), Streak);
	}

	UNiagaraComponent* SpawnSystem(UWorld* World, const TSoftObjectPtr<UNiagaraSystem>& System, const FVector& Location, const FRotator& Rotation)
	{
		if (!World || World->bIsTearingDown || World->GetNetMode() == NM_DedicatedServer)
		{
			return nullptr;
		}
		UNiagaraSystem* Asset = System.LoadSynchronous();
		if (!Asset)
		{
			return nullptr;
		}
		// AutoRelease: the component goes back to Niagara's per-world pool when
		// the effect ends, so steady fire reuses components instead of creating them.
		return UNiagaraFunctionLibrary::SpawnSystemAtLocation(World, Asset, Location, Rotation, FVector::OneVector,
			/*bAutoDestroy*/ true, /*bAutoActivate*/ true, ENCPoolMethod::AutoRelease, /*bPreCullCheck*/ true);
	}

	EPhysicalSurface SurfaceAt(UWorld* World, const FVector& Location, const FVector& Normal)
	{
		if (!World)
		{
			return SurfaceType_Default;
		}
		const FVector N = Normal.IsNearlyZero() ? FVector::UpVector : Normal.GetSafeNormal();
		FCollisionQueryParams Params(SCENE_QUERY_STAT(CSImpactSurface), false);
		Params.bReturnPhysicalMaterial = true;
		FHitResult Hit;
		if (!World->LineTraceSingleByChannel(Hit, Location + N * 5.f, Location - N * 10.f, ECC_Visibility, Params))
		{
			return SurfaceType_Default;
		}
		return UPhysicalMaterial::DetermineSurfaceType(Hit.PhysMaterial.Get());
	}

	void ShellEject(UWorld* World, const FTransform& Muzzle)
	{
		// Out of the ejection port (about a receiver length behind the muzzle),
		// to the right and a little up and back.
		const FVector Forward = Muzzle.GetRotation().GetForwardVector();
		const FVector Right = Muzzle.GetRotation().GetRightVector();
		const FVector Up = Muzzle.GetRotation().GetUpVector();
		const FVector Port = Muzzle.GetLocation() - Forward * 35.f + Right * 2.f + Up * 2.f;
		const FVector Out = (Right + Up * 0.5f - Forward * 0.2f).GetSafeNormal();
		SpawnSystem(World, ShellEjectSystem, Port, Out.Rotation());
	}

	void Impact(UWorld* World, const FVector& Location, const FVector& Normal, bool bHitPlayer)
	{
		if (!World)
		{
			return;
		}
		const FVector N = Normal.IsNearlyZero() ? FVector::UpVector : Normal.GetSafeNormal();
		const UCSAudioSettings* Audio = UCSAudioSettings::Get();

		// The systems throw their particles along +X: out of the surface.
		if (bHitPlayer)
		{
			SpawnSystem(World, BloodSystem, Location + N * 3.f, N.Rotation());
			CSAudio::PlayAt(World, Audio->BodyHit, Location + N * 5.f, 0.9f, FMath::FRandRange(0.92f, 1.08f), ECSSound::Impact);
			return;
		}

		// Sparks off metal, splinters off wood, clods off dirt, dust and chips
		// off everything else; the ricochet sound is pitched to match.
		const EPhysicalSurface Surface = SurfaceAt(World, Location, N);
		const TSoftObjectPtr<UNiagaraSystem>* System = &StoneImpactSystem;
		FVector2f Pitch(0.85f, 1.15f);
		float Volume = 0.7f;
		if (Surface == CSSurface::Metal)
		{
			System = &MetalImpactSystem;
			Pitch = FVector2f(1.15f, 1.4f);
		}
		else if (Surface == CSSurface::Wood)
		{
			System = &WoodImpactSystem;
			Pitch = FVector2f(0.72f, 0.88f);
		}
		else if (Surface == CSSurface::Dirt)
		{
			System = &DirtImpactSystem;
			Pitch = FVector2f(0.6f, 0.75f);
			Volume = 0.5f;
		}
		SpawnSystem(World, *System, Location + N * 2.f, N.Rotation());

		// Bullet hole, oriented into the surface.
		if (UMaterialInterface* Decal = BulletHoleMaterial.LoadSynchronous())
		{
			const float Size = FMath::FRandRange(6.f, 8.f);
			FRotator Rotation = (-N).Rotation();
			Rotation.Roll = FMath::FRandRange(-180.f, 180.f);
			if (UDecalComponent* Hole = UGameplayStatics::SpawnDecalAtLocation(World, Decal, FVector(4.f, Size, Size), Location, Rotation, GDecalLifetime))
			{
				Hole->SetFadeScreenSize(0.001f);
				Hole->SetFadeOut(GDecalLifetime - 3.f, 3.f, false);
			}
		}

		CSAudio::PlayAt(World, Audio->BulletImpact, Location + N * 5.f, Volume, FMath::FRandRange(Pitch.X, Pitch.Y), ECSSound::Impact);
	}

	void Explosion(UWorld* World, const FVector& Location)
	{
		SpawnSystem(World, ExplosionSystem, Location + FVector(0.f, 0.f, 20.f), FRotator(90.f, 0.f, 0.f));
	}

	void FlashbangBurst(UWorld* World, const FVector& Location)
	{
		SpawnSystem(World, FlashbangSystem, Location + FVector(0.f, 0.f, 15.f), FRotator(90.f, 0.f, 0.f));
	}
}
