// Copyright (c) 2026 CS-Fusion. All Rights Reserved.
//
// One data asset holding every Enhanced Input binding the character needs, so
// gameplay code never hard-references individual asset paths.
//
// Create the asset in the editor:
//   Content/Input/DA_CSInputConfig  (Miscellaneous > Data Asset > CSInputConfig)
//
// Scripts/bootstrap_content.py generates it along with the Input Actions and
// the Input Mapping Context.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "CSInputConfig.generated.h"

class UInputAction;
class UInputMappingContext;

UCLASS(BlueprintType)
class CSFUSION_API UCSInputConfig : public UDataAsset
{
	GENERATED_BODY()

public:
	/** Applied to the local player on possession. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input")
	TObjectPtr<UInputMappingContext> DefaultMappingContext;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input", meta = (ClampMin = "0"))
	int32 MappingPriority = 0;

	/** Axis2D: X = right/left, Y = forward/back. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input")
	TObjectPtr<UInputAction> IA_Move;

	/** Axis2D: X = yaw, Y = pitch. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input")
	TObjectPtr<UInputAction> IA_Look;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input")
	TObjectPtr<UInputAction> IA_Jump;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input")
	TObjectPtr<UInputAction> IA_Sprint;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input")
	TObjectPtr<UInputAction> IA_Crouch;

	// --- Reserved for Stage 2+ (declared now so the asset does not churn) ---

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Combat")
	TObjectPtr<UInputAction> IA_Fire;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Combat")
	TObjectPtr<UInputAction> IA_Aim;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Combat")
	TObjectPtr<UInputAction> IA_Reload;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Inventory")
	TObjectPtr<UInputAction> IA_Interact;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Inventory")
	TObjectPtr<UInputAction> IA_ToggleInventory;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|UI")
	TObjectPtr<UInputAction> IA_PauseMenu;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|UI")
	TObjectPtr<UInputAction> IA_Scoreboard;

	/**
	 * Axis1D. All number keys map here, each with a Scalar modifier equal to
	 * its number, so one binding handles every slot key.
	 */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Inventory")
	TObjectPtr<UInputAction> IA_EquipSlot;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Inventory")
	TObjectPtr<UInputAction> IA_Drop;

	// --- Runtime-built mapping context -------------------------------------
	//
	// The bindings are constructed in C++ rather than read from the
	// DefaultMappingContext asset. That asset is generated by
	// Scripts/bootstrap_content.py, and a Python-authored UInputMappingContext
	// is exactly the kind of artefact whose on-disk contents can look right
	// while behaving wrong - and it cannot be reviewed in a diff.
	//
	// Building here also gives Stage 8 rebindable keys somewhere real to live:
	// the defaults below are plain FKeys, editable per project and per player.

	/** Build the context this project actually uses. Never returns the asset. */
	UInputMappingContext* BuildRuntimeMappingContext(UObject* Outer) const;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Keys")
	FKey Key_MoveForward = EKeys::W;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Keys")
	FKey Key_MoveBack = EKeys::S;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Keys")
	FKey Key_MoveLeft = EKeys::A;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Keys")
	FKey Key_MoveRight = EKeys::D;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Keys")
	FKey Key_Look = EKeys::Mouse2D;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Keys")
	FKey Key_Jump = EKeys::SpaceBar;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Keys")
	FKey Key_Sprint = EKeys::LeftShift;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Keys")
	FKey Key_Crouch = EKeys::LeftControl;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Keys")
	FKey Key_Fire = EKeys::LeftMouseButton;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Keys")
	FKey Key_Aim = EKeys::RightMouseButton;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Keys")
	FKey Key_Reload = EKeys::R;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Keys")
	FKey Key_Interact = EKeys::E;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Keys")
	FKey Key_ToggleInventory = EKeys::Tab;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Keys")
	FKey Key_PauseMenu = EKeys::Escape;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Keys")
	FKey Key_Scoreboard = EKeys::BackSpace;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Keys")
	FKey Key_Drop = EKeys::G;

	/** Key 1 = starter pistol, keys 2..7 = inventory slots 1..6. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "CS|Input|Keys")
	TArray<FKey> SlotKeys = { EKeys::One, EKeys::Two, EKeys::Three, EKeys::Four, EKeys::Five, EKeys::Six, EKeys::Seven };
};
